<?php

namespace Admin\BabyFootBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FinalPhaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinalPhaseRepository extends EntityRepository
{
}
